helmDefaults:
  createNamespace: true

releases:
  - name: blobscan
    namespace: staging
    chart: blobscan/blobscan
    # chart: /home/.../blobscan-helm-charts/charts/blobscan
    version: 0.9.6
    values:
      - values.yaml
    secrets:
      - secrets.yaml
