helmDefaults:
  createNamespace: true

releases:
  - name: blobscan
    namespace: staging
    chart: blobscan/blobscan
    # chart: /home/.../blobscan-helm-charts/charts/blobscan
    version: 0.11.4
    values:
      - values.yaml
    secrets:
      - secrets.yaml

  - name: ipfs-gateway
    namespace: staging
    chart: ../../kubernetes/helm/ipfs-gateway
    values:
      - ingress:
          host: staging.blobscan.com
          tlsSecretName: staging-blobscan-tls
