creation_rules:
  - pgp: "FE7F3ABE1470369E0839081616EFB510AB8B3C4C"
    encrypted_regex: '^(DATABASE_URL|DIRECT_URL|REDIS_URI|SECRET_KEY|GOOGLE_SERVICE_KEY|GOOGLE_STORAGE_BUCKET_NAME|GOOGLE_STORAGE_PROJECT_ID|WEAVEVM_API_KEY|BEACON_NODE_ENDPOINT|EXECUTION_NODE_ENDPOINT|SENTRY_DSN|value|access-token|email|ETH_PRICE_SYNCER_CHAIN_JSON_RPC_URL|FEEDBACK_WEBHOOK_URL|SENTRY_DSN_API|WEAVEVM_API_KEY|password|keystorePassword)$'
