authKey: ENC[AES256_GCM,data:S/mXxwvAlEWD5EAgWXY5Q+E03N6uz8mwa1lLdcoPFz13rbm9bYg4Hhv7/sd5P1noAutGH7EDg+4RJ0oo4FEiwdP2iJ7MajmM1hkFimiSLpDKRE+2VpVV5A==,iv:+pOLx/qGUwqOsAj9cnuj5L0OXlGSwIQ4ukWRduJ9DQk=,tag:HSNmH6XqhVyLAAFiGdQBaQ==,type:str]
sops:
    lastmodified: "2026-06-24T13:53:41Z"
    mac: ENC[AES256_GCM,data:YsR6oLmMOXueOZvJvpQD7qbLlE2TGRN9UyGsgft4X2/HKm3Ka1LYcVTEf2oCEo5GrN4wVNvcC2XOqrPYFHSclNIiL4og/OLEUqyU+1O5M0+tl1vZBVj5XJhcZMc1wKXM+hna8Z5C+HFSoRWvaShD0g3nXRFU3IjFuaVXOailAuw=,iv:II3TzmNORXH3JG+h6n/UTyxRnlpFJoLGv4jcsyd6TBs=,tag:J/oX0PN6S/LWJPih+4q8jA==,type:str]
    pgp:
        - created_at: "2026-06-24T13:53:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hE4D21nlfAkoNNISAQdAMRHsddfBUCPvFQJ8xlqSUBYwh9gvtOqEbQyBRY9El0Ig
            vWlAP8Mx/u++qKj2IzbZkynZSnF0AwlG947fvsQ6V5HSXgEM7VJjftBE9zCUVflC
            D12LIFSKwWo6MeAibZRkvruZhfTEJbrnFd0XhuXRynAUOW85CdoTfxpSz0qSjzMN
            puslmEhNuiLJDBlMZS1YfGZy6rao1pvfKpdgVnPB6lQ=
            =R1Nc
            -----END PGP MESSAGE-----
          fp: FE7F3ABE1470369E0839081616EFB510AB8B3C4C
    unencrypted_regex: ^(enabled|provider|endpointURL|destinationPath|create|name|retentionPolicy|compression|maxParallel|encryption)$
    version: 3.13.1
