- name: Configure grafana in a Ethereum node
  ansible.builtin.import_tasks: ethereum_node.yml
  when: grafana_role == "ethereum_node"

- name: Configure grafana in a Blobscan node
  ansible.builtin.import_tasks: blobscan.yml
  when: grafana_role == "blobscan"
