helmDefaults:
  createNamespace: true

releases:
  - name: blobscan
    namespace: mainnet
    chart: blobscan/blobscan
    version: 0.9.6
    values:
      - values.yaml
    secrets:
      - secrets.yaml
