- name: Install common dependencies (apt)
  apt:
    update_cache: yes
    name:
      - bwm-ng
      - fail2ban
      - fd-find
      - htop
      - iotop
      - jq
      - ncdu
      - net-tools
      - python3-pip
      - rsync
      - tmux
      - vim
      - vnstat
      # Allows Ansible to become an unprivileged user
      # https://github.com/georchestra/ansible/issues/55#issuecomment-588313638
      - acl

# Workaround
# https://github.com/docker/docker-py/issues/3194
- name: Install Docker SDK for Python (workaround docker-py#3194)
  ansible.builtin.pip:
    name:
      - "docker==6.1.3"
      - "docker-compose"
