chain_id: 17000
explorer_base_url: https://dora.holesky.ethpandaops.io/
beacon_base_url: https://holesky.beaconcha.in/
consensus_checkpoint_sync_url: https://checkpoint-sync.holesky.ethpandaops.io/

swarm_storage_enabled: "true"
swarm_batch_id: "681516b8e343060758d495248a0912f6c4fde11ebf11e510b429a3c109bcabb2"
