# letsencrypt (api)

letsencrypt_certificates: [["api.{{ domain }}"]]
letsencrypt_email: "{{ vault_letsencrypt_email }}"

# grafana configuration

otlp_url: https://otlp-gateway-prod-eu-west-0.grafana.net/otlp
otlp_protocol: http/protobuf

# blobscan configuration

metrics_enabled: "true"
traces_enabled: "true"

indexer_log: blob_indexer=INFO

external_web_port: 3000
blobscan_api_port: 3001
external_api_port: 3001
blobscan_api_endpoint: "http://localhost:3001"

# secrets

database_url: "{{ vault_database_url }}"
secret_key: "{{ vault_secret_key }}"

bee_endpoint: "{{ vault_bee_endpoint }}"

gcs_bucket_name: "{{ vault_gcs_bucket_name }}"
google_project_id: "{{ vault_google_project_id }}"
google_service_key: "{{ vault_google_service_key }}"

sentry_dsn_api: "{{ vault_sentry_dsn_api }}"
sentry_dsn_indexer: "{{ vault_sentry_dsn_indexer }}"

redis_uri: "rediss://{{ vault_redis_user }}:{{ vault_redis_pass }}@{{ vault_redis_host }}:{{ vault_redis_port }}/{{ vault_redis_db }}"

otlp_auth_username: "{{ vault_otlp_auth_username }}"
otlp_auth_password: "{{ vault_otlp_auth_password }}"
