grafana_cloud_api_key: "{{ vault_grafana_cloud_api_key }}"
grafana_cloud_logs_api_key: "{{ vault_grafana_cloud_logs_api_key }}"
metrics_username: "{{ vault_metrics_username }}"
logs_username: "{{ vault_logs_username }}"
traces_username: "{{ vault_traces_username }}"

prometheus_url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
loki_url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
tempo_url: tempo-eu-west-0.grafana.net:443

beacon_node_metrics: http://localhost:8008
execution_node_metrics: http://localhost:6060

docker_network_name: "service_net"

# ethpandaops roles
ethereum_node_cl_checkpoint_sync_enabled: true
ethereum_metrics_exporter_container_ports:
  - "9095:9090"

ethstats_container_env:
  WS_SECRET: "{{ vault_ethstats_ws_secret }}"

lodestar_container_ports:
  - "0.0.0.0:{{ lodestar_ports_http_beacon }}:{{ lodestar_ports_http_beacon }}"
  - "{{ lodestar_ports_p2p_tcp }}:{{ lodestar_ports_p2p_tcp }}"
  - "{{ lodestar_ports_p2p_udp }}:{{ lodestar_ports_p2p_udp }}/udp"
  - "{{ lodestar_ports_metrics }}:{{ lodestar_ports_metrics }}"

nethermind_container_ports:
  - "0.0.0.0:{{ nethermind_ports_http_rpc }}:{{ nethermind_ports_http_rpc }}"
  - "0.0.0.0:{{ nethermind_ports_engine }}:{{ nethermind_ports_engine }}"
  - "{{ nethermind_ports_p2p }}:{{ nethermind_ports_p2p }}"
  - "{{ nethermind_ports_p2p }}:{{ nethermind_ports_p2p }}/udp"
  - "{{ nethermind_ports_metrics }}:{{ nethermind_ports_metrics }}"

nethermind_container_networks:
  - name: "{{ docker_network_name }}"

lodestar_container_networks:
  - name: "{{ docker_network_name }}"

ethereum_metrics_exporter_container_networks:
  - name: "{{ docker_network_name }}"
