---
- hosts: blobscan
  become: yes
  become_user: root

  vars:
    grafana_role: blobscan


  vars_files:
    - roles/blobscan/defaults/main.yml
    - roles/blobscan/vars/main.yml
    - roles/blobscan/vars/vault.yml
    - roles/blobscan/vars/{{ network }}.yml
    - inventory/{{ env }}/group_vars/all.yml
    - inventory/{{ env }}/group_vars/{{ network }}.yml
    - inventory/{{ env }}/group_vars/vault_{{ network }}.yml

  roles:
    - role: common
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true

    - role: blobscan
    - role: julienpalard.nginx_letsencrypt
  tasks:
    - name: Configure nginx as reverse proxy for Blobscan API
      template:
        src: ./roles/blobscan/templates/nginx-certbot.conf.j2
        dest: /etc/nginx/sites-available/blobscan-api.conf
      notify:
        - reload nginx
