---
- hosts: blobscan
  become: yes
  become_user: root

  vars_files:
    - roles/common/vars/vault.yml
    - environments/{{ env }}/group_vars/all
    - environments/{{ env }}/group_vars/vault.yml

  roles:
    - role: common
    - role: blobscan
