---
- hosts: blobscan
  become: yes
  become_user: root

  tasks:
    - name: Stop indexer container
      community.docker.docker_compose_v2:
        project_src: /home/deploy/blobscan-indexer.rs
        # Comment the following line to spin up the container (docker compose up)
        state: stopped
