---
- hosts: blobscan
  become: yes
  become_user: root

  vars:
    service_user: root
    service_group: root

  vars_files:
    - roles/blobscan_monitoring/vars/vault.yml
    - inventory/{{ env }}/group_vars/{{ network }}.yml

  roles:
    - role: blobscan_monitoring

- hosts: swarm
  become: yes
  become_user: root

  vars:
    service_user: root
    service_group: root

  vars_files:
    - roles/blobscan_monitoring/vars/vault.yml

  roles:
    - role: swarm_monitoring
