helmDefaults:
  createNamespace: true

releases:
  - name: blobscan
    namespace: hoodi
    chart: blobscan/blobscan
    version: 0.11.4
    values:
      - values.yaml
    secrets:
      - secrets.yaml

  - name: ipfs-gateway
    namespace: hoodi
    chart: ../../kubernetes/helm/ipfs-gateway
    values:
      - ingress:
          host: hoodi.blobscan.com
          tlsSecretName: hoodi-blobscan-tls
